### ISSUE TITLE
Reincarnate "Event Horizon" feature

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#110]
A version of Gameboard in development at one time provided a timeline visualizing player actions (e.g. attempts, correct submissions, etc.) during the course of their participation in a game or challenge. We've been asked to resurrect this feature (at a point yet undetermined).

This item requires additional discussion with the Gameboard team to scope development.

**Comment by sei-jmattson** [comment]
https://github.com/cmu-sei/gameboard-ui-v2/tree/master/src/app/ui/event-horizon

**Comment by sei-jbooz** [comment]
Related to #288

**Comment by sei-bstein** [comment]
Closing this for now, as this feature appears stable. If/when we need more from it, we can open issues to address as needed.
