### ISSUE TITLE
"Challenge Start Pending" error

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#112]
Reproduction steps:

1. Enroll in a game
2. Deploy a challenge
3. Deploy another challenge
4. On every subsequent deployment of a challenge, observe an error banner reading "Challenge Start Pending"

Repro video attached.

https://user-images.githubusercontent.com/115497763/217288080-a2239834-3e68-42fe-a2d8-8fc227821607.mp4

**Comment by sei-bstein** [comment]
Additional insight from @sei-jmattson suggests that that this is in some way related to the presence of the feedback form on the challenge page. Gameboard team suggests examining this component for accidental incorrect Observable use.

**Comment by sei-jmattson** [comment]
Yes, challenge-feedback component mangles the parent observable.  Also, probably shouldn't include that component on the page until challenge is ended.

**Comment by sei-bstein** [comment]
> Yes, challenge-feedback component mangles the parent observable. Also, probably shouldn't include that component on the page until challenge is ended.

We discussed this during our sprint kickoff yesterday, and @sei-mkaar / @sei-jbooz  asked me to see if it could be kept on the page (minimized by default) while the challenge is active. I wanted to ask you about this, actually - is the issue that the component is reusing an observable in the parent?

**Comment by sei-bstein** [comment]
Resolved by [3.9.0](https://github.com/cmu-sei/Gameboard/pull/150).
