### ISSUE TITLE
Redesign of the reporting section

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#126]
Members of the team have agreed that the Reports page in the Admin section of Gameboard would benefit from usability improvements and new features. Some initial ideas are:

- Clearer names and descriptions for existing reports
- The ability to parameterize relevant reports and to adjust those parameters while viewing them
- Infrastructure that makes adding new reports easier
- A customized presentation, per-report, of its data and features that best support what it communicates
- CSV export should be preserved (potentially to XLSX/PDF as well?)

Additional requirements from project leadership:

- Registration numbers per board per day (more likely to be a dynamic period of time with a day default)
  - **NOTE:** We'll need a solution for historical data. SQL server has temporal tables, but PGSql only supports this with an extension, and it's unclear how that will interoperate with EF
- How many unique users signed up for competition each year
- User/track participation
  - How many people engaged _only_ in a specific Track (Teams, A or B)?
  - How many did two of these, and which ones?
  - How many did all three?
- Per board metrics:
  - How many users per sponsor enrolled vs. actually played
  - How many teams from each sponsor enrolled vs. actually played
- Per challenge metrics:
  - How many partial vs. complete solves
  - Average points scored
  - Average time to complete solve
  - Stretch goal: among users who have the same partial solve (by questions), what was the average time?
- App usage metrics
  - Challenge deploy count
  - How many distinct users from each sponsor have an account?
  - TBD: how many actually play(?)

**Comment by sei-bstein** [comment]
Summary of questions the revamped reports may address (and how well they currently answer these questions):

| Question | Report | Answered | Notes |  
| --- | --- | --- |  --- |
| How many users played _only_ in a specific track? | Players Report | Y | -- | 
| How many users have ever started a session? | Engagment Report (pending) | N | -- |

**Comment by sei-bstein** [comment]
Additional points to address from internal review:

- Report for Prac?
- Distinguishing between team and individual performances on challenges (Challenges Report)
- Event Horizon data as report (#110)
- Challenge Report - use date range for deploy time
- Surface player-level info to players outside of the reporting section

**Comment by sei-bstein** [comment]
Todo: evaluate old reports to ensure necessary ones are ported forward.

**Comment by sei-bstein** [comment]
Request captured in another issue: average practice challenges completed per user (globally?)

**Comment by sei-jbooz** [comment]
Related to #209

**Comment by sei-bstein** [comment]
Updated our requirements table in [this comment](https://github.com/cmu-sei/Gameboard/issues/126#issuecomment-1560121423)

**Comment by sei-bstein** [comment]
This is a good place to track the updated Reporting effort, but I moved it to "Blocked" in the project because I don't expect us to have any bandwidth for it (except for minor issues) until late April.

**Comment by jbooz1** [comment]
Update from Stakeholders: 

We should port the old "Feedback Report" to the new reporting interface.

**Comment by sei-bstein** [comment]
Closed in favor of individual items as needed.
