### ISSUE TITLE
Review how elevated roles should function in the player-facing portion of the UI

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#158]
For discussion with product ownership: Should admins always act as admin in user-facing portions of the app (even when not explicitly invoking admin actions like "Admin Enroll"?)

Relates to `AsAdmin` style properties of requests.

**Comment by sei-jbooz** [comment]
Related to #157

**Comment by sei-bstein** [comment]
I'd say this is mostly handled by the roles rework. We don't support `AsAdmin` stuff anymore, and I mostly just asked this question because I didn't understand how Gameboard roles worked at the time.
