### ISSUE TITLE
New feature: access to limited subset of games (or limited time) for non-federal employees

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#162]
Project management indicates that we may need the ability to support limited use of the player-facing parts of gameboard for non-federal employees in the future. Requires additional discussion.

- What limitations do non-federal users have?
- How do they authenticate with Gameboard?
- Do they get additional help/prompts given that these are likely to be a different audience than our usual players?

**Comment by sei-jbooz** [comment]
No longer tracking as a GB feature
