### ISSUE TITLE
Enable review of previous submission attempts

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#165]
From stakeholders: 

> GB to provide competitors a way to view previous submission attempts. UI elements to restrict how users can see this information (e.g., can only see 1 question's previous answers at a time).

On hold pending discussion with project leads.

**Comment by sei-jbooz** [comment]
I think this request is similar to #135 and would benefit from being handled together.

**Comment by sei-bstein** [comment]
We're now okay with them seeing any number of (their own) historical submissions for the current challenge.

**Comment by sei-bstein** [comment]
Resolved in [3.14.0](https://github.com/cmu-sei/Gameboard/releases/tag/3.14.0).
