### ISSUE TITLE
Support -> Allow multiple users per ticket

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#167]
Stakeholders ask that we enable the association of multiple users to a ticket. Requires further discussion with project leads:

- Multiple players + multiple support?
- Who can add whom to the ticket?

**Comment by sei-jbooz** [comment]
This already exists within the context of a "Team" -- all members of the team can view the support ticket in their view. 

Closing this as "already implemented" for now. Can revisit later if needed.
