### ISSUE TITLE
Support -> Audible / prominent ticket notifications

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#168]
Stakeholders asked that we enable audible notifications when a ticket associated with the current user is updated. Potentially could do this via the browser Notification API - would need to expose configuration per user.

- Is this an opt-out feature?
- Prefer browser notification or another mechanism?

**Comment by sei-jbooz** [comment]
I think settings (radio buttons?) at the top of the Support tab to opt-out of notifications is good. 

- Play notification sound? Off / On  
- Send browser notification?  Off / On  

We can discuss the different types of notifications we can send and decide on what might be best.
