### ISSUE TITLE
Support -> Differentiate user responses in the ticket view

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#169]
From stakeholders:

> Differentiate user responses in the ticket UI by having different colored boxes. I am also thinking of a group-chat like UI for ticket comments. Comments from users with the Support Role appear on the right (like a text message that came from you), and comments from users without the support role appear on the left (like a text message that came from someone else). This type of visual distinction could help alleviate color-related issues (e.g., 509 compliance, does each user get their own color?, how many colors do we support?, etc.)

Pending additional discussion with project leads.

**Comment by sei-jbooz** [comment]
Released in GB 3.13.0
