### ISSUE TITLE
Console error: 401 on initial load of gameboard

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#181]
Initial load of the GB angular app produces a 401 (attached). Doesn't seem to impact behavior currently, but we generally try to minimize unnecessary console chatter.

![image](https://github.com/cmu-sei/Gameboard/assets/115497763/2c03a49e-6219-4483-8947-8187cbd58613)

**Comment by sei-jbooz** [comment]
No longer seeing
