### ISSUE TITLE
Integration of certificates with practice challenges

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#198]
For practice challenges:

- Show Title and Description of the challenge that they played
- Show time spent on challenge
- If a player does the same practice challenge more than once, show a certificate only for their most recent attempt.
- Certificates for all completed competitions and practice challenges should appear under the user's profile
- Practice mode to show an indicator that reminds the player whether or not they've completed the challenge in practice mode before (reveal completion date/ solve speed somewhere)

**Comment by sei-bstein** [comment]
Also score

**Comment by sei-jbooz** [comment]
Update: 

Only award certificates for full solves of practice challenges.  This means, we probably want to only award a certificate for the _first_ fully complete attempt for a practice challenge from a user.

**Comment by sei-bstein** [comment]
Resolved in [3.10.1](https://github.com/cmu-sei/Gameboard/releases/tag/3.10.1).
