### ISSUE TITLE
Overall site stats - Report

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#209]
Per stakeholders, not critical to deployment of Prac stuff, but will likely be useful later.

> We might also want a way to view overall site stats -- top 10 most popular games by enrollment, top 10 most popular challenges in competition mode by attempts, top 10 most popular practice challenges by attempts, these kinds of things

To discuss: should we present this as one or more reports, or is it more of a dashboard-style view with links into the reporting system? Where/how is it best visualized? How will site admins apply the knowledge they get from these stats?

**Comment by sei-bstein** [comment]
Other data of interest:

- How many challenges have ever been deployed (practice and competitive combined/separate)
- How many users have ever logged in
- How many users have ever deployed a challenge

**Comment by sei-bstein** [comment]
Beneficial to filter by date range.

**Comment by sei-jbooz** [comment]
How many new users?

**Comment by sei-bstein** [comment]
We broke these requirements into multiple smaller issues for simpler tracking.

- #308 - Enrollment report new tab
- #309  - new Players report
- #310 - new Challenges report
- #311 - potential global dashboard stats
