### ISSUE TITLE
Require authenticated user to select a sponsor on login (if they don't have one)

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#223]
Current implementation requires users to select a sponsor before registering for a game. With the advent of practice mode, we need to ensure they have a sponsor before playing those games too. As a result, we're moving to requiring users to have a sponsor.

1. Implement sponsor select dialog that pops on auth if they don't have a sponsor
2. Add route guards to the app to prevent access to all routes if they don't have a sponsor
3. Update/migrate domain model to make sponsor non-nullable (default to "other")

**Comment by sei-jbooz** [comment]
Related to #221

**Comment by sei-bstein** [comment]
Final plan:

- Sponsor is now not-nullable, and users are assigned a default sponsor on creation ("other" if it exists, otherwise the first sponsor in the table)
- Users table now has a `HasDefaultSponsor` flag which defaults to `true`.
- If the user's `HasDefaultSponsor` flag is on, they'll see a banner at the top of the app reminding them to choose a sponsor
- Users are prohibited from enrolling in games (or playing practice challenges) while their `HasDefaultSponsor` flag is true

**Comment by sei-bstein** [comment]
Resolved in [3.11.0](https://github.com/cmu-sei/Gameboard/compare/3.10.3...3.11.0).
