### ISSUE TITLE
ChallengeEvent for when users attempt to submit answers after their session expires

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#229]
Currently, when a user tries to submit an answer after their session has expired, Gameboard will simply not allow the submission. This is not tracked by a ChallengeEvent. 

When a user asks why their answer submission wasn't accepted, we look to see if there is a ChallengeEvent associated with their attempt, if there is not, then we assume the submission was after the session ended. 

Adding a ChallengeEvent will make this adjudication more definitive.

**Comment by sei-bstein** [comment]
Resolved with [v3.14.4](https://github.com/cmu-sei/Gameboard/releases/tag/3.14.4)
