### ISSUE TITLE
Link to Solution Guides in Practice Area

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#234]
Admins should be able to configure a "solution guide link" for each challenge and select if they want to publish that link when the challenge is in practice mode. 

If a solution guide link is marked as published for practice mode, then the link should be displayed with the challenge document in the practice mode interface.

**Comment by sei-bstein** [comment]
This is a really nice feature, and quite doable. A thing we have to keep in mind when we implement is that we have to be very careful not to expose the solution guide field in API responses if the challenge spec is attached to a game which is in competitive mode. For example, if someone creates the game in practice mode, sets the solution guide link, and then later sets the game to competitive, we need to either delete the link or hide it in responses.

**Comment by sei-jbooz** [comment]
Same as #179
