### ISSUE TITLE
Gameboard is not finishing some challenges fully

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#235]
Some Challenges in GB are not getting fully marked as "Finished".  They still have the green indicator in the Admin > Challenges interface and the Challenge JSON remains "isActive: true". 

![Image](https://github.com/cmu-sei/Gameboard/assets/89405171/2668f5c5-94f6-4de3-9d79-339cc9a3666c)

I don't see corresponding gamespaces in the TopoMojo Database for this challenge and others that are in limbo. 

Could this be from Challenge Devs killing the gamespaces in TopoMojo, therefore GB can't clean them up when it is time to expire them?

**Comment by sei-bstein** [comment]
Possibly. The intent is that challenges which are killed elsewhere get cleaned up by a recurring progress in Gameboard, but that process is the one that is currently getting tripped up by the async implementation in `JobService`. I'm going to leave this open to track that issue - once we resolve the `JobService` thing, we can review to see if this is still happening.

**Comment by sei-bstein** [comment]
I think I have this fixed, but we'll need to deploy it in QA to verify prior to release.
