### ISSUE TITLE
Practice challenge still looks available after time has expired

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#237]
Current behavior from the video attached: 

The time remaining in the practice session is 0. Cumulative Time continues to increase. TopoMojo has already destroyed the gamespace. Challenge questions and gamespace resources still appear available. Attempting to answer a question resets the UI to show the "Start Practice Session" button. 

Desired behavior: 
Upon session expiration, the UI should notify the user that their session has ended. Jumping right back to the "Start session" screen might be confusing, so maybe a modal that shows "Session expired" or the like. 

https://github.com/cmu-sei/Gameboard/assets/89405171/f18f86ef-74f4-4040-ae36-8fb77c69fef6

**Comment by sei-bstein** [comment]
Resolved in https://github.com/cmu-sei/Gameboard/commit/571e9bf31def7e0539aa6ef49bcc2d6f74c211d4.

**Comment by sei-bstein** [comment]
Resolved in [3.10.1](https://github.com/cmu-sei/Gameboard/releases/tag/3.10.1).
