### ISSUE TITLE
API Key UI element shows the current time when there are no API keys for a user

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#248]
The "Issued On" column is confusing when a user does not have any API keys. 

Hiding the current time between the Key Name and expiration date for new keys may reduce confusion. 

Steps to recreate: 
1. Navigate to Admin > Users and open details for a user
2. When a user does not have an API key, the API Key section will show that a key was issued at the current time. The database does not reflect an API Key creation. 
3. If you add a name to the API Key, the red `add` button turns green.
4. After clicking the green add button, the UI shows the API Key details
5. A new table is rendered when a user does have API Keys

![image](https://github.com/cmu-sei/Gameboard/assets/89405171/af3c03df-6ed7-4874-b021-af83cd602a32)

**Comment by sei-bstein** [comment]
Released as an accidental "ninja" fix in [3.17.2](https://github.com/cmu-sei/Gameboard/releases/tag/3.17.2).

**Comment by sei-bstein** [comment]
Disregard above - this is in for the release following 3.17.2.

**Comment by sei-bstein** [comment]
Headed out to the world with [3.18.0](https://github.com/cmu-sei/gameboard-ui/pull/180).
