### ISSUE TITLE
New games do not show an example default feedback configuration

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#256]
New games do not show an example default feedback configuration. 

Propose adding a tooltip similar to the one for Certificate Template that shows an example and instructions.

**Comment by sei-bstein** [comment]
I like this one! I think we did some encapsulation of the logic for the yaml config of challenge bonuses - that might be a path to consider as well (placeholder text which shows the example template, with the ability to paste it into the box with a click).

**Comment by sei-bstein** [comment]
This went out with 3.16.0 as a commit to the web client project.
