### ISSUE TITLE
Improvements to challenge spec sync

### ISSUE THREAD

**Issue by sei-bstein** [cmu-sei/Gameboard#269]
Gameboard builds the name, description, text, and tags of challenge specs from Topomojo workspaces. Currently, this only happens when a user manually initiates the sync from Admin -> Game settings or when a spec is added to a game. 

Given that these properties don't change anything about the actual process of solving the challenge, we'd like to reduce the burden of requiring a manual sync. Options include a recurring process (like the one we use to expire dead challenges) or an automatic sync when a spec is previewed.

**Comment by sei-jbooz** [comment]
Challenge Specs Synced with Game Engine (TopoMojo) on application startup released in [v3.12.0](https://github.com/cmu-sei/Gameboard/releases/tag/3.12.0). 

This is sufficient for now. We can revisit if the need arises.
