### ISSUE TITLE
Notification of new sponsors when logging in

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#299]
When someone logs in to GB for the first time after this update is pushed, we should show them a notification that there are new sponsors to choose from.  Optionally, we could make this notification appear _every time_ someone logs in after new sponsors are added rather than just this one time?

**Comment by sei-bstein** [comment]
Addressed this need via the new Notifications feature in 3.13.0. Notifications about sponsors can be configured in Admin.
