### ISSUE TITLE
UI - Support User Comments Make Links Hard to See

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#323]
When a support user enters a link into the newly colored support comments, the links are hard to read due to the colors. 

![image](https://github.com/cmu-sei/Gameboard/assets/89405171/f2e08245-1b49-4b71-b1cf-8929f0421cd8)

**Comment by sei-bstein** [comment]
Resolved in [v3.14.2](https://github.com/cmu-sei/Gameboard/releases/tag/3.14.2).
