### ISSUE TITLE
Game Map Editor is slow to respond

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#360]
When moving/resizing click-points on the game map editor, the UI is rapidly making requests to /config , /challengespecs , /specs , and /challengegates.   I think these rapid requests make the clickpoint editing a bit laggy.

**Comment by sei-bstein** [comment]
We're started on this, but it's very slightly more complex than it might first appear. My perspective is that this is really secondary to the "game editor" component being too large, functionally speaking. Solution is to refactor that component such that the map editor is its own thing and just raises events to listeners who might need to know that a spec's map properties have changed.

**Comment by sei-bstein** [comment]
Shipped in [3.21.0](https://github.com/cmu-sei/Gameboard/releases/tag/3.21.0).
