### ISSUE TITLE
Add toast for Refresh Specs

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#382]
GB recently added toast notifications for extending time and announcements. GB should do the same for the "Sync with Source" button for challenge specs. 

The toast should indicate success/failure when the request is finished.

**Comment by sei-bstein** [comment]
Resolved [here](https://github.com/cmu-sei/gameboard-ui/commit/b8c2a7cd4f071b319e79f51d251c38e239d9d460), will go out with our next update.

**Comment by sei-bstein** [comment]
Released with [3.16.0](https://github.com/cmu-sei/Gameboard/releases/tag/3.16.0).
