### ISSUE TITLE
Reporting Area: Feedback Report

### ISSUE THREAD

**Issue by jbooz1** [cmu-sei/Gameboard#465]
Port the old feedback report to the new reporting interface.

**Comment by sei-bstein** [comment]
Per internal discussions, we're currently planning on doing this as two reports in the new reporting module (one for games, another for challenges). This enables logical comparison for feedback across games/challenges. Currently slated for an August-ish release (at earliest).

**Comment by sei-bstein** [comment]
This'll go out in 3.21.0 as one report. We can't reasonably separate this into two reports, allowing for nice filtering, without revising how we do feedback templates (#494). But it's in the new Reports tab now.

**Comment by sei-bstein** [comment]
Shipped in [3.21.0](https://github.com/cmu-sei/Gameboard/releases/tag/3.21.0).
