### ISSUE TITLE
Game Center - Practice Tab

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#472]
New "Practice" tab in the game center to show player usage of the game in the practice area. 

This should include session timelines, scores, etc. that we would want to see for players. 

It is ok if a user appears in the table more than once (once per player record) but might be interesting to see if we could somehow compress that.  This could get tricky with timeline graphics if users are playing practice challenges from the game across an extended time period.

**Comment by sei-bstein** [comment]
Released in 3.20.0.
