### ISSUE TITLE
Admin > Game > Players -- Practice Filter Bug

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#473]
Navigating to Admin > Games > Hover over a game > Players > Apply the Practice Filter does not yield the expected results. 

The table showing players shows all having a score of 0. All timelines also show nothing other than "Gamespace Started". 

Expanding player details shows the correct information though. 

This could be related to #472 - if that is implemented and will replace this interface, then might not be worth spending a ton of time on fixing this up.

**Comment by sei-bstein** [comment]
This is resolved with the new "Practice" tab in Game Center (v3.20.0)
