### ISSUE TITLE
Practice Area Report Modals

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#474]
Let's consider making these stats show numbers (in addition to or instead of %) and make them clickable. Click should pop a modal that shows the player records.  Doesn't need to load too much data into the modal, IMO. 

![image](https://github.com/cmu-sei/Gameboard/assets/89405171/427f15ff-836c-4e05-958f-13ae77690c76)

**Comment by sei-bstein** [comment]
Related to #283 - Will confirm how the solution for that issue aligns with the need expressed here.

**Comment by sei-bstein** [comment]
We shipped this in 3.20.0.
