### ISSUE TITLE
Improve handling of unlimited submission attempts

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#499]
Currently, if you set a submission limit of `0` in GB, you should get unlimited submission attempts.  It has been reported that this is not respected in the practice area. We should make sure we allow that there.   Additionally, the submission counter should do something better than showing `Attempt 1 out of 0` when there are unlimited submission attempts.

**Comment by sei-bstein** [comment]
I'll be able to fold this into the work we're doing for the skilling labs ^
